import type { Metadata } from "next";
import { Geist, Azeret_Mono as Geist_Mono } from 'next/font/google';
import "./globals.css";
// import {GridBackground} from "../components/GridBackground";
// import { HeroGeometric } from "../components/GridBackground";
import Liquid from "@/components/Navbar";
import Footer from "@/components/Footer";
import MouseMoveEffect from "@/components/ui/mouse-move-effect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        {/* <GridBackground /> */}
        
        <Liquid />
        <MouseMoveEffect />
        {children}
        <Footer />
      </body>
    </html>
  );
}

